# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 487eebb74af697c7822079ecc870a5458fdc5e82c4691dde74eec3df4744aad3154670e7c8e90329935d072cba1e3aa5de811457fd63bc336c25d427142d6a5d

test:
  secret_key_base: 36750ab4f78205eefc8a8a2c017d36b440e07882b3d436bd14b73ded30c803e54b3fa7d5fb55d7077c33b1506aac85ecb18b829ed2a49d5a77da2f1dd3a179d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
