# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6149ab94778cc63735767f68b6481139549261faa32515c78a88a0ae1c60f91f8277dcc7ea633c478a4665a97953da33e2342cb8d6cf1983aeaae25626b35173

test:
  secret_key_base: c74483f2ca62c72be3147e19f7fad7fa43fe45003739165d5a0d1ece73eeef2fbf39f0aeb627fd04b006f06094f74a856bd0310a1604747001baa7c787cf2e6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
